query GetProjectByUri($uri: String!) {
  nodeByUri(uri: $uri) {
    __typename
    ... on Project {
      id
      status
      seo {
        title
        metaDesc
        canonical
      }
      projectHero {
        details {
          color
          coverMedia
          intro
          media {
            coverImage {
              node {
                altText
                sourceUrl
              }
            }
          }
          subtitle
          title
        }
      }
      projectContent {
        content {
          ... on ProjectContentContentTextLayout {
            __typename
            text {
              text
              width
            }
          }
          ... on ProjectContentContentImageLayout {
            __typename
            showCaption
            image {
              node {
                altText
                sourceUrl
              }
            }
            size
          }
          ... on ProjectContentContentVideoLayout {
            __typename
            embed
            embedCopy
            option
            size
            video {
              node {
                altText
                sourceUrl
              }
            }
          }
          ... on ProjectContentContentTestimonialLayout {
            __typename
            name
            photo {
              node {
                altText
                sourceUrl
              }
            }
            roleCompany
            testimonial
          }
          ... on ProjectContentContentMultiColsLayout {
            __typename
            col {
              showText
              tet
              text
              titlw
              verticalAlign
              video
              image {
                node {
                  altText
                  sourceUrl
                }
              }
            }
          }
          ... on ProjectContentContentColorModeLayout {
            __typename
            colorMode
            fieldGroupName
          }
          ... on ProjectContentContentGalleryLayout {
            __typename
            gallery {
              nodes {
                altText
                sourceUrl
              }
            }
          }
        }
      }
      projectMeta {
        credits
        projectClient {
          nodes {
            ... on Client {
              id
              title
            }
          }
        }
        related {
          nodes {
            ... on Project {
              id
              title
            }
          }
        }
        services {
          nodes {
            ... on Service {
              id
              title
            }
          }
        }
      }
    }
  }
}
