query GetSlideFields {
  slides {
    nodes {
      status
      slideFields {
        slideTitle
        videoUrl
        slideSub
        image {
          node {
            altText
            title
            sourceUrl
          }
        }
        link {
          url
          title
          target
        }
      }
    }
  }
}
